include:
  - project: 'acme-org/acme-images/semantic-release'
    ref: master
    file:
      - '/jobs_dotnet_v3.yml'

variables:
  dotnetcore_image: $DOCKER_REGISTRY/acme-dotnet:10.0
  NUGET_PACKAGES_DIRECTORY: 'nuget_packages'
  VERSION: 1.0.0
  solution_file: src/Aftermath.slnx

image: $GITLAB_RUNNER_DOCKER_IMAGE

cache:
  key: "nuget"
  paths:
    - '$NUGET_PACKAGES_DIRECTORY'

stages:
  - build

build:
  variables:
    packageVersion: $VERSION.$CI_PIPELINE_IID
  before_script:
    - shopt -s expand_aliases
    - alias nuget="mono /usr/local/bin/nuget.exe"
    - git remote prune origin
    - git fetch --all
    - dotnet restore $solution_file --packages $CI_PROJECT_DIR/$NUGET_PACKAGES_DIRECTORY
  stage: build
  image: $dotnetcore_image
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
  script:
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "main" || "$CI_COMMIT_REF_NAME" =~ ^release\/.*$ ]]; then
        packageVersion="$VERSION.$CI_PIPELINE_IID"
      else
        packageVersion="$VERSION-beta.$CI_PIPELINE_IID"
      fi
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet sonarscanner begin /k:"Aftermath" /d:sonar.host.url="$SONAR_HOST" /d:sonar.login="$SONAR_LOGIN" /d:sonar.qualitygate.wait=true /d:sonar.inclusions="**/*.cs" /d:sonar.msbuild.testProjectPattern="**/*.Tests/**/*.cs"
    - dotnet build --no-restore $solution_file --packages $CI_PROJECT_DIR/$NUGET_PACKAGES_DIRECTORY --configuration Release --output $CI_PROJECT_DIR/dist /p:Version=$packageVersion
    - dotnet test src/Aftermath.Tests/Aftermath.Tests.csproj --no-restore --configuration Release
    - dotnet sonarscanner end /d:sonar.login="${SONAR_LOGIN}"
    - nuget push dist/Aftermath.$packageVersion.nupkg -ApiKey $NUGET_API_KEY -Source $NUGET_SERVER
  tags:
    - DockerLinux

trivy-scan:
  stage: build
  rules:
    - when: never
  dependencies: []
